### ISSUE TITLE
Code is semi-finished product？？？

### ISSUE THREAD

**Issue by gzhuxiaomogu** [theFool32/UAP_retrieval#2]
in the extract_rank.py ,
model = init_network(
        model=state["meta"]["architecture"],
        pooling=state["meta"]["pooling"],
        whitening=state["meta"]["whitening"],
        mean=state["meta"]["mean"],
        std=state["meta"]["std"],
        pretrained=False,
    )
This  init_network function has no param model ? And the code have many error like this. Do you run the code successfully?

**Comment by theFool32** [comment]
Sorry for not noticing that cnnimageretrieval-pytorch is still updating now.
The code is based on the previous version (`c4fca89` commit).

**Comment by gzhuxiaomogu** [comment]
Thanks
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jie Li"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月29日(星期天) 晚上6:23
收件人:&nbsp;"theFool32/UAP_retrieval"<UAP_retrieval@noreply.github.com&gt;;
抄送:&nbsp;"围城"<2361576922@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [theFool32/UAP_retrieval] Code is semi-finished product？？？ (#2)




Sorry for not noticing that cnnimageretrieval-pytorch is still updating now.
 The code is based on the previous version (c4fca89 commit).

**Comment by theFool32** [comment]
> Thanks

Modified because your email address is leaked (still accessible).
Maybe you can delete it if you care about this.

**Comment by gzhuxiaomogu** [comment]
Is there anything wrong with the class MultiLoss in the attack./myutil/utils.py? The variable **w** never seems to be mentioned.

**Comment by theFool32** [comment]
The `MultiLoss` is proposed in [1]. Though I define it here, I don't use it actually as in `attack/attack.py`

[1] Kendall, Alex, Yarin Gal, and Roberto Cipolla. "Multi-task learning using uncertainty to weigh losses for scene geometry and semantics." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2018.

**Comment by gzhuxiaomogu** [comment]
The function ImagesFromList has no param random on filipradenovic/cnnimageretrieval-pytorch (Commit c4fca89), but ImagesFromList has a param random in attack/extract_rank.py. Why?

**Comment by theFool32** [comment]
`random` is used to augment the data with random resolution.
This part of codes along with `cnnimageretrieval-pytorch` code base will be uploaded recently.

**Comment by gujingzi** [comment]
> in the extract_rank.py ,
> model = init_network(
> model=state["meta"]["architecture"],
> pooling=state["meta"]["pooling"],
> whitening=state["meta"]["whitening"],
> mean=state["meta"]["mean"],
> std=state["meta"]["std"],
> pretrained=False,
> )
> This init_network function has no param model ? And the code have many error like this. Do you run the code successfully?

 model = init_network(
        model=state["meta"]["architecture"],
        pooling=state["meta"]["pooling"],
        whitening=state["meta"]["whitening"],
        mean=state["meta"]["mean"],
        std=state["meta"]["std"],
        pretrained=False,
    )
    model.load_state_dict(state["state_dict"])
    model.meta["Lw"] = state["meta"]["Lw"]
in c4fca89, i can not find Lw
